"""changes

Revision ID: 2d2d1b4d3b86
Revises: 1836d4b402d5
Create Date: 2024-08-10 17:43:12.590064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d2d1b4d3b86'
down_revision: Union[str, None] = '1836d4b402d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_ibfk_2', 'admin', type_='foreignkey')
    op.drop_column('admin', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('admin_ibfk_2', 'admin', 'md_user_status', ['status_id'], ['status_id'])
    # ### end Alembic commands ###
