"""ttest

Revision ID: 50c2b54dbcb6
Revises: 
Create Date: 2024-08-11 09:24:00.639805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50c2b54dbcb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('admin', 'status_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'status_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('admin', 'last_login')
    # ### end Alembic commands ###
