"""First Time

Revision ID: 8f2e20008bae
Revises: ec0aea978aea
Create Date: 2024-08-11 20:41:59.606159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2e20008bae'
down_revision: Union[str, None] = 'ec0aea978aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('md_countries', sa.Column('currencySymbol', sa.String(length=100), nullable=True))
    op.add_column('md_countries', sa.Column('currencyCode', sa.String(length=100), nullable=True))
    op.add_column('md_countries', sa.Column('allowNumAndCharInZipcode', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('md_countries', 'allowNumAndCharInZipcode')
    op.drop_column('md_countries', 'currencyCode')
    op.drop_column('md_countries', 'currencySymbol')
    # ### end Alembic commands ###
