"""changes

Revision ID: 94fac333ddbe
Revises: 2d2d1b4d3b86
Create Date: 2024-08-10 17:47:21.092149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94fac333ddbe'
down_revision: Union[str, None] = '2d2d1b4d3b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_ibfk_1', 'admin', type_='foreignkey')
    op.drop_column('admin', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('admin_ibfk_1', 'admin', 'md_user_roles', ['role_id'], ['role_id'])
    # ### end Alembic commands ###
