"""User Details Added

Revision ID: b057f4f05152
Revises: 8f2e20008bae
Create Date: 2024-08-12 06:49:00.528216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b057f4f05152'
down_revision: Union[str, None] = '8f2e20008bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_detais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['md_countries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['md_locations.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['md_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_detais_country_id'), 'user_detais', ['country_id'], unique=False)
    op.create_index(op.f('ix_user_detais_location_id'), 'user_detais', ['location_id'], unique=False)
    op.create_index(op.f('ix_user_detais_state_id'), 'user_detais', ['state_id'], unique=False)
    op.create_index(op.f('ix_user_detais_user_id'), 'user_detais', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_detais_user_id'), table_name='user_detais')
    op.drop_index(op.f('ix_user_detais_state_id'), table_name='user_detais')
    op.drop_index(op.f('ix_user_detais_location_id'), table_name='user_detais')
    op.drop_index(op.f('ix_user_detais_country_id'), table_name='user_detais')
    op.drop_table('user_detais')
    # ### end Alembic commands ###
