"""Your message here

Revision ID: e21d72c49c01
Revises: 2bcdae9b3f06
Create Date: 2024-08-10 18:01:11.386673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21d72c49c01'
down_revision: Union[str, None] = '2bcdae9b3f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'role_id')
    # ### end Alembic commands ###
